-- =============================================================
-- ÓPTICA ALBA - SUPABASE / POSTGRESQL
-- Angular se conecta mediante supabase-js.
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- =============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================
-- FUNCIONES GENERALES
-- =============================================================

CREATE OR REPLACE FUNCTION public.fn_actualizar_fecha_modificacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.actualizado_en = NOW();
  RETURN NEW;
END;
$$;

-- =============================================================
-- USUARIOS Y ROLES
-- =============================================================

CREATE TABLE IF NOT EXISTS public.roles (
  id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE,
  descripcion VARCHAR(160),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_roles_nombre CHECK (nombre IN ('ADMINISTRADOR', 'VENDEDOR'))
);

INSERT INTO public.roles (nombre, descripcion)
VALUES
  ('ADMINISTRADOR', 'Acceso completo al sistema'),
  ('VENDEDOR', 'Ventas, clientes, recetas y consulta de inventario')
ON CONFLICT (nombre) DO UPDATE SET descripcion = EXCLUDED.descripcion;

CREATE TABLE IF NOT EXISTS public.usuarios (
  id_usuario UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  id_rol BIGINT NOT NULL REFERENCES public.roles(id_rol),
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(120) NOT NULL DEFAULT '',
  email VARCHAR(180) NOT NULL UNIQUE,
  telefono VARCHAR(25),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_acceso TIMESTAMPTZ,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.fn_crear_perfil_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rol TEXT;
  v_id_rol BIGINT;
BEGIN
  v_rol := UPPER(COALESCE(NEW.raw_user_meta_data->>'rol', 'VENDEDOR'));
  IF v_rol NOT IN ('ADMINISTRADOR', 'VENDEDOR') THEN
    v_rol := 'VENDEDOR';
  END IF;

  SELECT id_rol INTO v_id_rol
  FROM public.roles
  WHERE nombre = v_rol;

  INSERT INTO public.usuarios (
    id_usuario, id_rol, nombres, apellidos, email, telefono
  ) VALUES (
    NEW.id,
    v_id_rol,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'nombres', ''), split_part(COALESCE(NEW.email, 'Usuario'), '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'apellidos', ''),
    COALESCE(NEW.email, NEW.id::TEXT || '@sin-correo.local'),
    NULLIF(NEW.raw_user_meta_data->>'telefono', '')
  )
  ON CONFLICT (id_usuario) DO UPDATE SET
    email = EXCLUDED.email,
    nombres = EXCLUDED.nombres,
    apellidos = EXCLUDED.apellidos,
    telefono = EXCLUDED.telefono,
    actualizado_en = NOW();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auth_usuario_creado ON auth.users;
CREATE TRIGGER trg_auth_usuario_creado
AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.fn_crear_perfil_usuario();

CREATE OR REPLACE FUNCTION public.fn_usuario_activo()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id_usuario = auth.uid()
      AND u.activo = TRUE
  );
$$;

CREATE OR REPLACE FUNCTION public.fn_es_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.usuarios u
    JOIN public.roles r ON r.id_rol = u.id_rol
    WHERE u.id_usuario = auth.uid()
      AND u.activo = TRUE
      AND r.nombre = 'ADMINISTRADOR'
  );
$$;

-- =============================================================
-- CLIENTES Y RECETAS
-- =============================================================

CREATE TABLE IF NOT EXISTS public.clientes (
  id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_persona VARCHAR(15) NOT NULL DEFAULT 'NATURAL',
  tipo_documento VARCHAR(20) NOT NULL DEFAULT 'DNI',
  numero_documento VARCHAR(20),
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL DEFAULT '',
  razon_social VARCHAR(180),
  telefono VARCHAR(25),
  email VARCHAR(180),
  direccion VARCHAR(250),
  fecha_nacimiento DATE,
  observaciones TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_clientes_tipo_persona CHECK (tipo_persona IN ('NATURAL', 'JURIDICA')),
  CONSTRAINT chk_clientes_tipo_documento CHECK (tipo_documento IN ('DNI', 'RUC', 'CE', 'PASAPORTE', 'SIN_DOCUMENTO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_clientes_documento
ON public.clientes(tipo_documento, numero_documento)
WHERE numero_documento IS NOT NULL AND numero_documento <> '' AND tipo_documento <> 'SIN_DOCUMENTO';

CREATE TABLE IF NOT EXISTS public.recetas_opticas (
  id_receta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente BIGINT NOT NULL REFERENCES public.clientes(id_cliente) ON DELETE CASCADE,
  fecha_receta DATE NOT NULL DEFAULT CURRENT_DATE,
  profesional VARCHAR(160),

  lejos_od_esfera NUMERIC(7,2),
  lejos_od_cilindro NUMERIC(7,2),
  lejos_od_eje SMALLINT,
  lejos_oi_esfera NUMERIC(7,2),
  lejos_oi_cilindro NUMERIC(7,2),
  lejos_oi_eje SMALLINT,
  lejos_dip NUMERIC(7,2),

  cerca_od_esfera NUMERIC(7,2),
  cerca_od_cilindro NUMERIC(7,2),
  cerca_od_eje SMALLINT,
  cerca_oi_esfera NUMERIC(7,2),
  cerca_oi_cilindro NUMERIC(7,2),
  cerca_oi_eje SMALLINT,
  cerca_dip NUMERIC(7,2),

  diagnostico TEXT,
  observaciones TEXT,
  vigente BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_receta_lejos_od_eje CHECK (lejos_od_eje IS NULL OR lejos_od_eje BETWEEN 0 AND 180),
  CONSTRAINT chk_receta_lejos_oi_eje CHECK (lejos_oi_eje IS NULL OR lejos_oi_eje BETWEEN 0 AND 180),
  CONSTRAINT chk_receta_cerca_od_eje CHECK (cerca_od_eje IS NULL OR cerca_od_eje BETWEEN 0 AND 180),
  CONSTRAINT chk_receta_cerca_oi_eje CHECK (cerca_oi_eje IS NULL OR cerca_oi_eje BETWEEN 0 AND 180)
);

-- =============================================================
-- CATÁLOGOS E INVENTARIO
-- =============================================================

CREATE TABLE IF NOT EXISTS public.categorias (
  id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(250),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.categorias(nombre, descripcion)
VALUES
  ('Monturas', 'Monturas oftálmicas y solares'),
  ('Lunas', 'Lunas ópticas y tratamientos'),
  ('Lentes de contacto', 'Lentes de contacto graduados y cosméticos'),
  ('Estuches', 'Estuches para lentes'),
  ('Líquidos limpiadores', 'Soluciones y limpiadores'),
  ('Paños', 'Paños de limpieza'),
  ('Accesorios', 'Cordones, sujetadores y accesorios'),
  ('Repuestos', 'Tornillos, plaquetas y repuestos'),
  ('Otros', 'Otros productos de óptica')
ON CONFLICT (nombre) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.marcas (
  id_marca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.proveedores (
  id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento VARCHAR(20) NOT NULL DEFAULT 'RUC',
  numero_documento VARCHAR(20),
  razon_social VARCHAR(180) NOT NULL,
  nombre_contacto VARCHAR(160),
  telefono VARCHAR(25),
  email VARCHAR(180),
  direccion VARCHAR(250),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_proveedor_tipo_documento CHECK (tipo_documento IN ('RUC', 'DNI', 'CE', 'OTRO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_proveedor_documento
ON public.proveedores(tipo_documento, numero_documento)
WHERE numero_documento IS NOT NULL AND numero_documento <> '';

CREATE TABLE IF NOT EXISTS public.productos (
  id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria BIGINT NOT NULL REFERENCES public.categorias(id_categoria),
  id_marca BIGINT REFERENCES public.marcas(id_marca),
  id_proveedor_preferido BIGINT REFERENCES public.proveedores(id_proveedor),
  codigo_interno VARCHAR(60) NOT NULL UNIQUE,
  codigo_barras VARCHAR(100) NOT NULL UNIQUE,
  nombre VARCHAR(180) NOT NULL,
  descripcion TEXT,
  modelo VARCHAR(120),
  color VARCHAR(80),
  medida VARCHAR(100),
  material VARCHAR(100),
  precio_compra NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (precio_compra >= 0),
  precio_venta NUMERIC(12,2) NOT NULL CHECK (precio_venta >= 0),
  stock_actual INTEGER NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
  stock_minimo INTEGER NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- COMPRAS (PREPARADAS PARA CRECIMIENTO)
-- =============================================================

CREATE TABLE IF NOT EXISTS public.compras (
  id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_compra VARCHAR(40) NOT NULL UNIQUE,
  id_proveedor BIGINT NOT NULL REFERENCES public.proveedores(id_proveedor),
  id_usuario UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  tipo_documento VARCHAR(30) NOT NULL DEFAULT 'FACTURA',
  numero_documento VARCHAR(60),
  fecha_compra TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA' CHECK (estado IN ('REGISTRADA', 'ANULADA')),
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.detalle_compras (
  id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra BIGINT NOT NULL REFERENCES public.compras(id_compra) ON DELETE CASCADE,
  id_producto BIGINT NOT NULL REFERENCES public.productos(id_producto),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- CAJA, VENTAS Y DETALLES
-- =============================================================

CREATE TABLE IF NOT EXISTS public.cajas (
  id_caja BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  monto_apertura NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (monto_apertura >= 0),
  fecha_cierre TIMESTAMPTZ,
  monto_cierre_real NUMERIC(12,2),
  monto_esperado NUMERIC(12,2),
  diferencia NUMERIC(12,2),
  estado VARCHAR(15) NOT NULL DEFAULT 'ABIERTA' CHECK (estado IN ('ABIERTA', 'CERRADA')),
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_caja_abierta_usuario
ON public.cajas(id_usuario)
WHERE estado = 'ABIERTA';

CREATE TABLE IF NOT EXISTS public.ventas (
  id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_venta VARCHAR(60) NOT NULL UNIQUE,
  id_cliente BIGINT REFERENCES public.clientes(id_cliente),
  id_usuario UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  id_caja BIGINT REFERENCES public.cajas(id_caja),
  fecha_venta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tipo_comprobante VARCHAR(20) NOT NULL DEFAULT 'ORDEN_TRABAJO' CHECK (tipo_comprobante IN ('ORDEN_TRABAJO', 'TICKET', 'NOTA_VENTA', 'BOLETA', 'FACTURA')),
  serie_comprobante VARCHAR(15),
  numero_comprobante VARCHAR(30),
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  a_cuenta NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (a_cuenta >= 0),
  saldo NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (saldo >= 0),
  metodo_pago VARCHAR(20) NOT NULL CHECK (metodo_pago IN ('EFECTIVO', 'YAPE', 'TRANSFERENCIA')),
  estado_pago VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pago IN ('PENDIENTE', 'PARCIAL', 'PAGADO')),
  estado_venta VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA' CHECK (estado_venta IN ('REGISTRADA', 'ANULADA')),
  observaciones TEXT,
  motivo_anulacion TEXT,
  anulado_por UUID REFERENCES public.usuarios(id_usuario),
  anulado_en TIMESTAMPTZ,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_venta_adelanto CHECK (a_cuenta <= total)
);

CREATE TABLE IF NOT EXISTS public.detalle_ventas (
  id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta BIGINT NOT NULL REFERENCES public.ventas(id_venta) ON DELETE CASCADE,
  id_producto BIGINT NOT NULL REFERENCES public.productos(id_producto),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  descuento NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
  subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.movimientos_inventario (
  id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto BIGINT NOT NULL REFERENCES public.productos(id_producto),
  id_usuario UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  tipo_movimiento VARCHAR(30) NOT NULL CHECK (tipo_movimiento IN (
    'ENTRADA_INICIAL', 'ENTRADA_COMPRA', 'SALIDA_VENTA', 'AJUSTE_ENTRADA', 'AJUSTE_SALIDA',
    'ANULACION_VENTA', 'ANULACION_COMPRA', 'DEVOLUCION_CLIENTE', 'DEVOLUCION_PROVEEDOR'
  )),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  stock_anterior INTEGER NOT NULL CHECK (stock_anterior >= 0),
  stock_nuevo INTEGER NOT NULL CHECK (stock_nuevo >= 0),
  referencia_tipo VARCHAR(40),
  referencia_id BIGINT,
  motivo VARCHAR(300),
  fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.movimientos_caja (
  id_movimiento_caja BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_caja BIGINT NOT NULL REFERENCES public.cajas(id_caja),
  id_usuario UUID NOT NULL DEFAULT auth.uid() REFERENCES public.usuarios(id_usuario),
  id_venta BIGINT REFERENCES public.ventas(id_venta),
  tipo_movimiento VARCHAR(20) NOT NULL CHECK (tipo_movimiento IN ('INGRESO', 'EGRESO')),
  concepto VARCHAR(300) NOT NULL,
  monto NUMERIC(12,2) NOT NULL CHECK (monto > 0),
  fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- CONFIGURACIÓN Y AUDITORÍA
-- =============================================================

CREATE TABLE IF NOT EXISTS public.configuracion_empresa (
  id_configuracion SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id_configuracion = 1),
  ruc VARCHAR(11),
  razon_social VARCHAR(180),
  nombre_comercial VARCHAR(180) NOT NULL,
  direccion VARCHAR(250),
  telefono VARCHAR(25),
  email VARCHAR(180),
  moneda VARCHAR(10) NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN', 'USD')),
  porcentaje_igv NUMERIC(5,2) NOT NULL DEFAULT 18 CHECK (porcentaje_igv BETWEEN 0 AND 100),
  ancho_ticket_mm SMALLINT NOT NULL DEFAULT 80 CHECK (ancho_ticket_mm IN (58, 80)),
  mensaje_ticket VARCHAR(300) DEFAULT 'Gracias por su compra',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.configuracion_empresa(id_configuracion, nombre_comercial)
VALUES (1, 'Óptica Alba')
ON CONFLICT (id_configuracion) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.auditoria (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario UUID REFERENCES public.usuarios(id_usuario),
  accion VARCHAR(100) NOT NULL,
  entidad VARCHAR(100) NOT NULL,
  id_registro BIGINT,
  datos_anteriores JSONB,
  datos_nuevos JSONB,
  fecha_evento TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- TRIGGERS updated_at
-- =============================================================

DO $$
DECLARE
  tabla TEXT;
BEGIN
  FOREACH tabla IN ARRAY ARRAY[
    'usuarios','clientes','recetas_opticas','categorias','marcas','proveedores','productos',
    'compras','ventas','configuracion_empresa'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'trg_' || tabla || '_actualizado', tabla);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_fecha_modificacion()',
      'trg_' || tabla || '_actualizado', tabla
    );
  END LOOP;
END;
$$;

-- =============================================================
-- FUNCIONES TRANSACCIONALES PARA ANGULAR
-- =============================================================

CREATE OR REPLACE FUNCTION public.crear_producto(
  p_codigo_interno TEXT,
  p_codigo_barras TEXT,
  p_nombre TEXT,
  p_descripcion TEXT,
  p_modelo TEXT,
  p_color TEXT,
  p_medida TEXT,
  p_material TEXT,
  p_precio_compra NUMERIC,
  p_precio_venta NUMERIC,
  p_stock_inicial INTEGER,
  p_stock_minimo INTEGER,
  p_id_categoria BIGINT,
  p_id_marca BIGINT,
  p_id_proveedor BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_producto public.productos%ROWTYPE;
  v_codigo_interno TEXT;
BEGIN
  IF NOT public.fn_es_admin() THEN
    RAISE EXCEPTION 'Solo el administrador puede crear productos';
  END IF;

  IF COALESCE(TRIM(p_codigo_barras), '') = '' OR COALESCE(TRIM(p_nombre), '') = '' THEN
    RAISE EXCEPTION 'Código de barras y nombre son obligatorios';
  END IF;

  v_codigo_interno := COALESCE(NULLIF(TRIM(p_codigo_interno), ''), TRIM(p_codigo_barras));

  INSERT INTO public.productos(
    id_categoria, id_marca, id_proveedor_preferido, codigo_interno, codigo_barras,
    nombre, descripcion, modelo, color, medida, material, precio_compra, precio_venta,
    stock_actual, stock_minimo
  ) VALUES (
    p_id_categoria, p_id_marca, p_id_proveedor, v_codigo_interno, TRIM(p_codigo_barras),
    TRIM(p_nombre), NULLIF(TRIM(p_descripcion), ''), NULLIF(TRIM(p_modelo), ''),
    NULLIF(TRIM(p_color), ''), NULLIF(TRIM(p_medida), ''), NULLIF(TRIM(p_material), ''),
    COALESCE(p_precio_compra, 0), COALESCE(p_precio_venta, 0),
    GREATEST(COALESCE(p_stock_inicial, 0), 0), GREATEST(COALESCE(p_stock_minimo, 0), 0)
  ) RETURNING * INTO v_producto;

  IF v_producto.stock_actual > 0 THEN
    INSERT INTO public.movimientos_inventario(
      id_producto, id_usuario, tipo_movimiento, cantidad, stock_anterior, stock_nuevo,
      referencia_tipo, referencia_id, motivo
    ) VALUES (
      v_producto.id_producto, auth.uid(), 'ENTRADA_INICIAL', v_producto.stock_actual,
      0, v_producto.stock_actual, 'PRODUCTO', v_producto.id_producto, 'Stock inicial del producto'
    );
  END IF;

  RETURN jsonb_build_object('id_producto', v_producto.id_producto);
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_cliente_receta(
  p_nombres TEXT,
  p_numero_documento TEXT,
  p_telefono TEXT,
  p_email TEXT,
  p_direccion TEXT,
  p_fecha_receta DATE,
  p_observaciones TEXT,
  p_lejos_od_esfera NUMERIC,
  p_lejos_od_cilindro NUMERIC,
  p_lejos_od_eje NUMERIC,
  p_lejos_oi_esfera NUMERIC,
  p_lejos_oi_cilindro NUMERIC,
  p_lejos_oi_eje NUMERIC,
  p_lejos_dip NUMERIC,
  p_cerca_od_esfera NUMERIC,
  p_cerca_od_cilindro NUMERIC,
  p_cerca_od_eje NUMERIC,
  p_cerca_oi_esfera NUMERIC,
  p_cerca_oi_cilindro NUMERIC,
  p_cerca_oi_eje NUMERIC,
  p_cerca_dip NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id_cliente BIGINT;
  v_tiene_receta BOOLEAN;
BEGIN
  IF NOT public.fn_usuario_activo() THEN
    RAISE EXCEPTION 'Usuario no autorizado';
  END IF;
  IF COALESCE(TRIM(p_nombres), '') = '' THEN
    RAISE EXCEPTION 'El nombre del cliente es obligatorio';
  END IF;

  INSERT INTO public.clientes(
    tipo_persona, tipo_documento, numero_documento, nombres, telefono, email,
    direccion, observaciones, creado_por
  ) VALUES (
    'NATURAL',
    CASE WHEN COALESCE(TRIM(p_numero_documento), '') = '' THEN 'SIN_DOCUMENTO' ELSE 'DNI' END,
    NULLIF(TRIM(p_numero_documento), ''),
    TRIM(p_nombres), NULLIF(TRIM(p_telefono), ''), NULLIF(TRIM(p_email), ''),
    NULLIF(TRIM(p_direccion), ''), NULLIF(TRIM(p_observaciones), ''), auth.uid()
  ) RETURNING id_cliente INTO v_id_cliente;

  v_tiene_receta :=
    p_lejos_od_esfera IS NOT NULL OR p_lejos_od_cilindro IS NOT NULL OR p_lejos_od_eje IS NOT NULL OR
    p_lejos_oi_esfera IS NOT NULL OR p_lejos_oi_cilindro IS NOT NULL OR p_lejos_oi_eje IS NOT NULL OR
    p_lejos_dip IS NOT NULL OR p_cerca_od_esfera IS NOT NULL OR p_cerca_od_cilindro IS NOT NULL OR
    p_cerca_od_eje IS NOT NULL OR p_cerca_oi_esfera IS NOT NULL OR p_cerca_oi_cilindro IS NOT NULL OR
    p_cerca_oi_eje IS NOT NULL OR p_cerca_dip IS NOT NULL;

  IF v_tiene_receta THEN
    INSERT INTO public.recetas_opticas(
      id_cliente, fecha_receta,
      lejos_od_esfera, lejos_od_cilindro, lejos_od_eje,
      lejos_oi_esfera, lejos_oi_cilindro, lejos_oi_eje, lejos_dip,
      cerca_od_esfera, cerca_od_cilindro, cerca_od_eje,
      cerca_oi_esfera, cerca_oi_cilindro, cerca_oi_eje, cerca_dip,
      observaciones, creado_por
    ) VALUES (
      v_id_cliente, COALESCE(p_fecha_receta, CURRENT_DATE),
      p_lejos_od_esfera, p_lejos_od_cilindro, p_lejos_od_eje::SMALLINT,
      p_lejos_oi_esfera, p_lejos_oi_cilindro, p_lejos_oi_eje::SMALLINT, p_lejos_dip,
      p_cerca_od_esfera, p_cerca_od_cilindro, p_cerca_od_eje::SMALLINT,
      p_cerca_oi_esfera, p_cerca_oi_cilindro, p_cerca_oi_eje::SMALLINT, p_cerca_dip,
      NULLIF(TRIM(p_observaciones), ''), auth.uid()
    );
  END IF;

  RETURN jsonb_build_object('id_cliente', v_id_cliente);
END;
$$;

CREATE OR REPLACE FUNCTION public.ajustar_inventario(
  p_id_producto BIGINT,
  p_tipo_movimiento TEXT,
  p_cantidad INTEGER,
  p_motivo TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_producto public.productos%ROWTYPE;
  v_nuevo_stock INTEGER;
  v_es_entrada BOOLEAN;
BEGIN
  IF NOT public.fn_es_admin() THEN
    RAISE EXCEPTION 'Solo el administrador puede ajustar el inventario';
  END IF;
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE EXCEPTION 'La cantidad debe ser mayor que cero';
  END IF;
  IF p_tipo_movimiento NOT IN ('AJUSTE_ENTRADA','AJUSTE_SALIDA','DEVOLUCION_CLIENTE','DEVOLUCION_PROVEEDOR') THEN
    RAISE EXCEPTION 'Tipo de movimiento inválido';
  END IF;

  SELECT * INTO v_producto
  FROM public.productos
  WHERE id_producto = p_id_producto
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Producto no encontrado'; END IF;

  v_es_entrada := p_tipo_movimiento IN ('AJUSTE_ENTRADA','DEVOLUCION_CLIENTE');
  v_nuevo_stock := CASE WHEN v_es_entrada
    THEN v_producto.stock_actual + p_cantidad
    ELSE v_producto.stock_actual - p_cantidad
  END;

  IF v_nuevo_stock < 0 THEN
    RAISE EXCEPTION 'Stock insuficiente para realizar la salida';
  END IF;

  UPDATE public.productos
  SET stock_actual = v_nuevo_stock
  WHERE id_producto = p_id_producto;

  INSERT INTO public.movimientos_inventario(
    id_producto,id_usuario,tipo_movimiento,cantidad,stock_anterior,stock_nuevo,motivo
  ) VALUES (
    p_id_producto,auth.uid(),p_tipo_movimiento,p_cantidad,v_producto.stock_actual,v_nuevo_stock,NULLIF(TRIM(p_motivo),'')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_venta(
  p_id_cliente BIGINT,
  p_metodo_pago TEXT,
  p_a_cuenta NUMERIC,
  p_observaciones TEXT,
  p_detalles JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id_venta BIGINT;
  v_numero_venta TEXT;
  v_total NUMERIC(12,2) := 0;
  v_a_cuenta NUMERIC(12,2);
  v_saldo NUMERIC(12,2);
  v_estado_pago TEXT;
  v_item JSONB;
  v_producto public.productos%ROWTYPE;
  v_cantidad INTEGER;
  v_descuento NUMERIC(12,2);
  v_subtotal NUMERIC(12,2);
  v_id_caja BIGINT;
BEGIN
  IF NOT public.fn_usuario_activo() THEN
    RAISE EXCEPTION 'Usuario no autorizado';
  END IF;
  IF p_metodo_pago NOT IN ('EFECTIVO','YAPE','TRANSFERENCIA') THEN
    RAISE EXCEPTION 'Método de pago inválido';
  END IF;
  IF p_detalles IS NULL OR jsonb_typeof(p_detalles) <> 'array' OR jsonb_array_length(p_detalles) = 0 THEN
    RAISE EXCEPTION 'La venta debe contener productos';
  END IF;

  SELECT id_caja INTO v_id_caja
  FROM public.cajas
  WHERE id_usuario = auth.uid() AND estado = 'ABIERTA'
  ORDER BY fecha_apertura DESC
  LIMIT 1;

  INSERT INTO public.ventas(
    numero_venta,id_cliente,id_usuario,id_caja,subtotal,total,a_cuenta,saldo,
    metodo_pago,estado_pago,estado_venta,observaciones
  ) VALUES (
    'TEMP-' || gen_random_uuid()::TEXT,p_id_cliente,auth.uid(),v_id_caja,0,0,0,0,
    p_metodo_pago,'PENDIENTE','REGISTRADA',NULLIF(TRIM(p_observaciones),'')
  ) RETURNING id_venta INTO v_id_venta;

  v_numero_venta := 'OT-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || LPAD(v_id_venta::TEXT, 6, '0');

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_detalles)
  LOOP
    v_cantidad := COALESCE((v_item->>'cantidad')::INTEGER, 0);
    v_descuento := GREATEST(COALESCE((v_item->>'descuento')::NUMERIC, 0), 0);
    IF v_cantidad <= 0 THEN RAISE EXCEPTION 'Cantidad inválida'; END IF;

    SELECT * INTO v_producto
    FROM public.productos
    WHERE id_producto = (v_item->>'producto_id')::BIGINT
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'Producto no encontrado'; END IF;
    IF NOT v_producto.activo THEN RAISE EXCEPTION 'El producto % está inactivo', v_producto.nombre; END IF;
    IF v_producto.stock_actual < v_cantidad THEN
      RAISE EXCEPTION 'Stock insuficiente para %: disponible %, solicitado %', v_producto.nombre, v_producto.stock_actual, v_cantidad;
    END IF;

    v_subtotal := GREATEST((v_producto.precio_venta * v_cantidad) - v_descuento, 0);

    INSERT INTO public.detalle_ventas(id_venta,id_producto,cantidad,precio_unitario,descuento,subtotal)
    VALUES (v_id_venta,v_producto.id_producto,v_cantidad,v_producto.precio_venta,v_descuento,v_subtotal);

    UPDATE public.productos
    SET stock_actual = stock_actual - v_cantidad
    WHERE id_producto = v_producto.id_producto;

    INSERT INTO public.movimientos_inventario(
      id_producto,id_usuario,tipo_movimiento,cantidad,stock_anterior,stock_nuevo,
      referencia_tipo,referencia_id,motivo
    ) VALUES (
      v_producto.id_producto,auth.uid(),'SALIDA_VENTA',v_cantidad,
      v_producto.stock_actual,v_producto.stock_actual-v_cantidad,
      'VENTA',v_id_venta,'Salida por venta ' || v_numero_venta
    );

    v_total := v_total + v_subtotal;
  END LOOP;

  v_a_cuenta := LEAST(GREATEST(COALESCE(p_a_cuenta, 0), 0), v_total);
  v_saldo := v_total - v_a_cuenta;
  v_estado_pago := CASE
    WHEN v_a_cuenta = 0 THEN 'PENDIENTE'
    WHEN v_saldo = 0 THEN 'PAGADO'
    ELSE 'PARCIAL'
  END;

  UPDATE public.ventas
  SET numero_venta = v_numero_venta,
      subtotal = v_total,
      total = v_total,
      a_cuenta = v_a_cuenta,
      saldo = v_saldo,
      estado_pago = v_estado_pago
  WHERE id_venta = v_id_venta;

  IF p_metodo_pago = 'EFECTIVO' AND v_a_cuenta > 0 AND v_id_caja IS NOT NULL THEN
    INSERT INTO public.movimientos_caja(id_caja,id_usuario,id_venta,tipo_movimiento,concepto,monto)
    VALUES (v_id_caja,auth.uid(),v_id_venta,'INGRESO','Cobro de ' || v_numero_venta,v_a_cuenta);
  END IF;

  INSERT INTO public.auditoria(id_usuario,accion,entidad,id_registro,datos_nuevos)
  VALUES (auth.uid(),'REGISTRAR_VENTA','ventas',v_id_venta,jsonb_build_object('numero',v_numero_venta,'total',v_total));

  RETURN jsonb_build_object(
    'id_venta',v_id_venta,
    'numero_venta',v_numero_venta,
    'total',v_total,
    'a_cuenta',v_a_cuenta,
    'saldo',v_saldo,
    'estado_pago',v_estado_pago
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.anular_venta(p_id_venta BIGINT, p_motivo TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_venta public.ventas%ROWTYPE;
  v_detalle RECORD;
  v_stock_anterior INTEGER;
BEGIN
  IF NOT public.fn_es_admin() THEN
    RAISE EXCEPTION 'Solo el administrador puede anular ventas';
  END IF;
  IF COALESCE(TRIM(p_motivo), '') = '' THEN
    RAISE EXCEPTION 'Debe indicar el motivo de anulación';
  END IF;

  SELECT * INTO v_venta FROM public.ventas WHERE id_venta = p_id_venta FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Venta no encontrada'; END IF;
  IF v_venta.estado_venta = 'ANULADA' THEN RAISE EXCEPTION 'La venta ya fue anulada'; END IF;

  FOR v_detalle IN SELECT * FROM public.detalle_ventas WHERE id_venta = p_id_venta
  LOOP
    SELECT stock_actual INTO v_stock_anterior
    FROM public.productos
    WHERE id_producto = v_detalle.id_producto
    FOR UPDATE;

    UPDATE public.productos
    SET stock_actual = stock_actual + v_detalle.cantidad
    WHERE id_producto = v_detalle.id_producto;

    INSERT INTO public.movimientos_inventario(
      id_producto,id_usuario,tipo_movimiento,cantidad,stock_anterior,stock_nuevo,
      referencia_tipo,referencia_id,motivo
    ) VALUES (
      v_detalle.id_producto,auth.uid(),'ANULACION_VENTA',v_detalle.cantidad,
      v_stock_anterior,v_stock_anterior+v_detalle.cantidad,'VENTA',p_id_venta,
      'Anulación de ' || v_venta.numero_venta
    );
  END LOOP;

  UPDATE public.ventas
  SET estado_venta='ANULADA',motivo_anulacion=TRIM(p_motivo),anulado_por=auth.uid(),anulado_en=NOW()
  WHERE id_venta=p_id_venta;

  INSERT INTO public.auditoria(id_usuario,accion,entidad,id_registro,datos_anteriores,datos_nuevos)
  VALUES (auth.uid(),'ANULAR_VENTA','ventas',p_id_venta,to_jsonb(v_venta),jsonb_build_object('motivo',TRIM(p_motivo)));
END;
$$;

-- =============================================================
-- ÍNDICES Y VISTAS
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON public.usuarios(id_rol);
CREATE INDEX IF NOT EXISTS idx_clientes_nombre ON public.clientes(nombres, apellidos);
CREATE INDEX IF NOT EXISTS idx_recetas_cliente_fecha ON public.recetas_opticas(id_cliente, fecha_receta DESC);
CREATE INDEX IF NOT EXISTS idx_productos_nombre ON public.productos(nombre);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON public.productos(id_categoria);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON public.ventas(fecha_venta DESC);
CREATE INDEX IF NOT EXISTS idx_ventas_cliente ON public.ventas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_detalle_ventas_producto ON public.detalle_ventas(id_producto);
CREATE INDEX IF NOT EXISTS idx_mov_inv_producto_fecha ON public.movimientos_inventario(id_producto, fecha_movimiento DESC);

CREATE OR REPLACE VIEW public.vw_productos_stock_bajo
WITH (security_invoker = true)
AS
SELECT
  p.id_producto,p.codigo_interno,p.codigo_barras,p.nombre,
  c.nombre AS categoria,m.nombre AS marca,p.stock_actual,p.stock_minimo,p.precio_venta
FROM public.productos p
JOIN public.categorias c ON c.id_categoria=p.id_categoria
LEFT JOIN public.marcas m ON m.id_marca=p.id_marca
WHERE p.activo=TRUE AND p.stock_actual<=p.stock_minimo;

CREATE OR REPLACE VIEW public.vw_ventas_diarias
WITH (security_invoker = true)
AS
SELECT
  DATE(v.fecha_venta) AS fecha,
  COUNT(*) FILTER (WHERE v.estado_venta='REGISTRADA') AS cantidad_ventas,
  COALESCE(SUM(v.total) FILTER (WHERE v.estado_venta='REGISTRADA'),0) AS total_vendido,
  COALESCE(SUM(v.a_cuenta) FILTER (WHERE v.estado_venta='REGISTRADA' AND v.metodo_pago='EFECTIVO'),0) AS total_efectivo,
  COALESCE(SUM(v.a_cuenta) FILTER (WHERE v.estado_venta='REGISTRADA' AND v.metodo_pago='YAPE'),0) AS total_yape,
  COALESCE(SUM(v.a_cuenta) FILTER (WHERE v.estado_venta='REGISTRADA' AND v.metodo_pago='TRANSFERENCIA'),0) AS total_transferencia
FROM public.ventas v
GROUP BY DATE(v.fecha_venta);

CREATE OR REPLACE VIEW public.vw_productos_mas_vendidos
WITH (security_invoker = true)
AS
SELECT
  p.id_producto,p.codigo_interno,p.nombre,
  COALESCE(SUM(dv.cantidad),0) AS unidades_vendidas,
  COALESCE(SUM(dv.subtotal),0) AS importe_vendido
FROM public.productos p
JOIN public.detalle_ventas dv ON dv.id_producto=p.id_producto
JOIN public.ventas v ON v.id_venta=dv.id_venta AND v.estado_venta='REGISTRADA'
GROUP BY p.id_producto,p.codigo_interno,p.nombre;

CREATE OR REPLACE VIEW public.vw_dashboard_resumen
WITH (security_invoker = true)
AS
SELECT
  COALESCE((SELECT SUM(total) FROM public.ventas WHERE estado_venta='REGISTRADA'),0) AS total_ventas,
  COALESCE((SELECT COUNT(*) FROM public.ventas WHERE estado_venta='REGISTRADA'),0) AS cantidad_ventas,
  COALESCE((SELECT COUNT(*) FROM public.productos WHERE activo=TRUE),0) AS total_productos,
  COALESCE((SELECT COUNT(*) FROM public.productos WHERE activo=TRUE AND stock_actual<=stock_minimo),0) AS bajo_stock,
  COALESCE((SELECT COUNT(*) FROM public.movimientos_inventario),0) AS movimientos_inventario;

-- =============================================================
-- ROW LEVEL SECURITY
-- =============================================================

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recetas_opticas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marcas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cajas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_caja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas anteriores para que el script pueda repetirse tras una corrección.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN SELECT schemaname, tablename, policyname FROM pg_policies WHERE schemaname='public'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
  END LOOP;
END;
$$;

CREATE POLICY roles_select ON public.roles FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY usuarios_select ON public.usuarios FOR SELECT TO authenticated USING (id_usuario=auth.uid() OR public.fn_es_admin());
CREATE POLICY usuarios_admin_update ON public.usuarios FOR UPDATE TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());

CREATE POLICY clientes_select ON public.clientes FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY clientes_insert ON public.clientes FOR INSERT TO authenticated WITH CHECK (public.fn_usuario_activo());
CREATE POLICY clientes_update ON public.clientes FOR UPDATE TO authenticated USING (public.fn_usuario_activo()) WITH CHECK (public.fn_usuario_activo());

CREATE POLICY recetas_select ON public.recetas_opticas FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY recetas_insert ON public.recetas_opticas FOR INSERT TO authenticated WITH CHECK (public.fn_usuario_activo());
CREATE POLICY recetas_update ON public.recetas_opticas FOR UPDATE TO authenticated USING (public.fn_usuario_activo()) WITH CHECK (public.fn_usuario_activo());

CREATE POLICY categorias_select ON public.categorias FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY categorias_admin_all ON public.categorias FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY marcas_select ON public.marcas FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY marcas_admin_all ON public.marcas FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY proveedores_select ON public.proveedores FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY proveedores_admin_all ON public.proveedores FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY productos_select ON public.productos FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY productos_admin_all ON public.productos FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());

CREATE POLICY compras_admin_all ON public.compras FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY detalle_compras_admin_all ON public.detalle_compras FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY cajas_select ON public.cajas FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY cajas_admin_all ON public.cajas FOR ALL TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());

CREATE POLICY ventas_select ON public.ventas FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY detalle_ventas_select ON public.detalle_ventas FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY movimientos_inventario_select ON public.movimientos_inventario FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY movimientos_caja_select ON public.movimientos_caja FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY configuracion_select ON public.configuracion_empresa FOR SELECT TO authenticated USING (public.fn_usuario_activo());
CREATE POLICY configuracion_admin_update ON public.configuracion_empresa FOR UPDATE TO authenticated USING (public.fn_es_admin()) WITH CHECK (public.fn_es_admin());
CREATE POLICY auditoria_admin_select ON public.auditoria FOR SELECT TO authenticated USING (public.fn_es_admin());

-- Permisos de funciones. La clave service_role nunca se coloca en Angular.
REVOKE ALL ON FUNCTION public.crear_producto(TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,NUMERIC,NUMERIC,INTEGER,INTEGER,BIGINT,BIGINT,BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.crear_producto(TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,NUMERIC,NUMERIC,INTEGER,INTEGER,BIGINT,BIGINT,BIGINT) TO authenticated;
REVOKE ALL ON FUNCTION public.registrar_cliente_receta(TEXT,TEXT,TEXT,TEXT,TEXT,DATE,TEXT,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_cliente_receta(TEXT,TEXT,TEXT,TEXT,TEXT,DATE,TEXT,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC,NUMERIC) TO authenticated;
REVOKE ALL ON FUNCTION public.ajustar_inventario(BIGINT,TEXT,INTEGER,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ajustar_inventario(BIGINT,TEXT,INTEGER,TEXT) TO authenticated;
REVOKE ALL ON FUNCTION public.registrar_venta(BIGINT,TEXT,NUMERIC,TEXT,JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_venta(BIGINT,TEXT,NUMERIC,TEXT,JSONB) TO authenticated;
REVOKE ALL ON FUNCTION public.anular_venta(BIGINT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.anular_venta(BIGINT,TEXT) TO authenticated;

GRANT SELECT ON public.vw_productos_stock_bajo, public.vw_ventas_diarias, public.vw_productos_mas_vendidos, public.vw_dashboard_resumen TO authenticated;

COMMIT;

-- =============================================================
-- CREAR EL PRIMER ADMINISTRADOR
-- =============================================================
-- 1) En Supabase > Authentication > Users > Add user.
-- 2) Luego ejecuta, reemplazando el correo:
--
-- UPDATE public.usuarios
-- SET id_rol=(SELECT id_rol FROM public.roles WHERE nombre='ADMINISTRADOR')
-- WHERE email='TU_CORREO_ADMIN';
-- =============================================================
